config/routes.rb
Rails.application.routes.draw do

  resources :products
  resources :teams
  root 'frontpage#index'
  get 'frontpage/index'

  resources :articles, only: [:show, :index]

  namespace :admin do
    resources :articles
    resources :teams
    resources :products
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  def news_view
    @article = Article.find(params[:id])
  end
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  layout 'admin'
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::AdminController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to [:admin, @article], notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to [:admin, @article], notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to admin_articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.fetch(:article, {}).permit(:body, :title)
    end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
  before_action :set_admin_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to [:admin, @product], notice: 'Team member was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to [:admin, @product], notice: 'Team member was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_team_members_url, notice: 'Team member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_admin_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.fetch(:product, {}).permit(:title, :description, :avatar, :price, :size, :other)
  end
end

app/controllers/admin/teams_controller.rb
class Admin::TeamsController < Admin::AdminController
  before_action :set_admin_teams, only: [:show, :edit, :update, :destroy]

  def index
    @teams = Team.all
  end

  def show
  end

  def new
    @team = Team.new
  end

  def edit
  end

  def create
    @team = Teams.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to [:admin, @team], notice: 'Team member was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @team.update(team_member_params)
        format.html { redirect_to [:admin, @team], notice: 'Team member was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to admin_teams_url, notice: 'Team member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_admin_team
    @team = Team.find(params[:id])
  end

  def team_params
    params.fetch(:team, {}).permit(:name, :bio, :avatar, :sponsors)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def show
    @article = Article.find(params[:id])
  end

  def index
    @articles = Article.all
  end
end

app/controllers/frontpage_controller.rb
class FrontpageController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def show
    @products = Product.find(params[:id])
  end

  def index
    @products = Product.all
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def show
    @team = Team.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/frontpage_helper.rb
module FrontpageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/_partials/_about.html.haml
#section-about
  .container
    %h1 ABOUT US
    .row
      .col-md-6.col-md-offset-3.col-xs-12
        %p.about-col-mid.text-center One answer is that Truth pertains to the possibility that an event will occur. Must all possible events occur?

  .container
    .row
      .col-md-6.col-xs-12
        .col-md-2.col-xs-3
          =image_tag("", class: 'about-image')
        .col-md-8.col-xs-9
          %p.about-col1
            A statement which remains a mere potential seems to exist only in the nether land between truth and falsity.
      .col-md-6.col-xs-12
        %p.about-col2
          Lorem ipsum dolor sit amet, quo at justo noster tamquam, has hinc gubergren intellegebat et. Aliquip maiorum ea mei, errem tamquam torquatos an quo, quot dissentias sed et. Quot omnium ne mel, possim commodo quaestio eos ex, paulo utamur sadipscing vis ad. Nostrum propriae no vis, his sanctus incorrupte in. No aperiri labitur scaevola mei. Saperet contentiones vis id. Ad eam incorrupte interesset, pri noster possit aliquip at.
          Dolorum efficiendi ei eos, in cum autem epicuri. Ne nam deserunt expetendis, labores tractatos voluptaria et eam. Te nec sonet fierent eleifend. Ferri invenire ocurreret ex mel.

app/views/_partials/_contact.html.haml
#section-contact
  .container-fluid
    .row
      .col-md-5.col-sm-5
        .row
          #map
      .col-md-7.col-sm-7
        .row
          .contact-elements
            =image_tag"", class: 'contact-logo'
            %h1=t('home_general.in-touch')
        .row
          .contact-wrapper
            .col-md-6.col-sm-6
              %p.bold-font CLUJ OFFICE
              &nbsp
              %p.light-font 22 Avram Iancu,
              %p.light-font 400071,
              %p.light-font Cluj-Napoca România
              &nbsp
              %p.light-font T (40-364) 98 67 54; 33 98 67
              %p.light-font F (40-364) 33 98 67
              %p.light-font E mail cluj.office@maxim.ro
            .col-md-6.col-sm-6
              %p.bold-font BUCHAREST OFFICE
              &nbsp
              %p.light-font 4-8 Dorobantilor Sector 1,
              %p.light-font 011141,
              %p.light-font București România
              &nbsp
              %p.light-font T (40-21) 584 77 66
              %p.light-font F (40-21) 584 77 66
              %p.light-font E mail office@maxim.ro
        %form.contact-form{:action => "", :method => "post", :nonvalidate => "", :target => "_blank"}
          .row
            .col-md-6.col-sm-6
              .group
                %input.input-margin{:name => "NAME", :required => "", :type => "text", :value => ""}/
                %span.bar
                %label=t('form_general.name')
            .col-md-6.col-sm-6
              .group
                %input.email-input{:name => "EMAIL", :required => "", :type => "text", :value => ""}/
                %span.highlight
                %span.bar
                %label=t('form_general.email')
          .row.subject-row
            .col-md-12.col-sm-12
              .group
                %input.subject-input{:name => "SUBJECT", :required => "", :type => "text", :value => ""}/
                %span.highlight
                %span.bar
                %label=t('form_general.subject')
          .row.message-row
            .col-md-12.col-sm-12
              %textarea.message-input.textarea{:cols => "80", :name => "MESSAGE", :placeholder => "Message", :required => "", :rows => "5", :value => ""}=t('form_general.message')
          .row
            .col-md-6.col-sm-6.pull-right
              %button.button.button-contact{:name => "button", :type => "submit"}=t('form_general.send')
          .row
            #success.alert.alert-success.display-none{:role => "alert"}
              %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
                %span{"aria-hidden" => "true"} ×
              %strong Success!
              Your email has been sent successfully!
            #danger.alert.alert-danger.display-none{:role => "alert"}
              %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
                %span{"aria-hidden" => "true"} ×
              %strong Error!
              Your email has not been sent!

app/views/_partials/_footer.html.haml
#section-footer
  .container-fluid
    .row
      .col-md-12.col-xs-12
        .col-md-10.col-xs-12
          %ul.footer-menu
            %li= link_to t('menu.home')
            %li= link_to t('menu.team')
            %li= link_to t('menu.products')
            %li= link_to t('menu.news')
            %li= link_to t('menu.contact')
        .col-md-2.col-xs-12
          %p.text-copyright.pull-right Copyright

app/views/_partials/_header.html.haml
%header
  %section#section-header
    .container-fluid
      .row
        .parallax

app/views/_partials/_nav.html.haml
%nav.navbar.nav-bar.navbar-nav.navbar-default.navbar-fixed-top
  .container
    .row
      .col-md-3.col-xs-12.pull-left
        .navbar-header
          %button.c-hamburger.c-hamburger--htx.collapsed.visible-sm.visible-xs.pull-right{"aria-expanded" => "false", "data-target" => "#navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span toggle menu
          %a.navbar-brand{:href => "/#section-header"}
      .col-md-6.pull-left.visible-md.visible-lg
        %ul.nav.navbar-nav.pull-right
          %li
            %a{:href => "/#section-header"}= t('menu.home')
          %li
            %a{:href => "/#section-products"}= t('menu.products')  
          %li
            %a{:href => "/#section-team"}= t('menu.team')
          %li= link_to t('menu.news')
          %li
            %a{:href => "/#section-contact"}= t('menu.contact')

      .hidden-lg.hidden-md
        .col-md-6.collapse.navbar-collapse#navbar-collapse-1
          %ul.nav-menu.mobile-menu
            %li
              %a{:href => "/#section-header"}= t('menu.home')
            %li
              %a{:href => "/#section-team"}= t('menu.team')
            %li= link_to t('menu.news')
            %li
              %a{:href => "/#section-contact"}= t('menu.contact')
      .col-md-2.col-sm-2.pull-right.hidden-sm.hidden-xs
        .nav-buttons
          %a
            %button.button.button-phone 0789.567.432

app/views/admin/articles/_form.html.haml
= form_for [:admin, @article] do |f|
  - if article.errors.any?
    #error_explanation
      %h2
        = pluralize(article.errors.count, "error")
        prohibited this article from being saved:
      %ul
        - article.errors.full_messages.each do |message|
          %li= message
  %form
    .form-group.row
      %label.bold-font=t('article.title')
      = f.text_field :title, require: true, class: 'form-control'
    .form-group.row
      %label.bold-font=t('admin_form.content')
      = f.text_area :body, :cols => 50, :rows => 10, require: true, class: 'form-control'
    .form-group.row
      %button.button-admin-save.pull-right{:type => "submit"}=t('article.save')

app/views/admin/articles/edit.html.haml
.article-body
  .container
    %h1=t('article.edit')
    = render 'form', article: @article
    .form-inline.row
      %button.button-admin-nav{:type => "submit"}= link_to t('admin_form.show'), [:admin, @article]
      %button.button-admin-nav{:type => "submit"}= link_to t('admin_form.back'), admin_articles_path

app/views/admin/articles/index.html.haml
.article-body
  .container
    %h1=t('article.list')
    .form-group.row
      %button.button-admin-nav{:type => "submit"}= link_to t('article.new'), new_admin_article_path
    - @articles.each do |article|
      %form.form-margin-bottom
        .form-group.row
          %label.bold-font.col-sm-2.checkbox=t('article.title')
          .col-sm-10
            %p.form-control-static= article.title
        .form-group.row
          %label.bold-font.col-sm-2.checkbox=t('admin_form.content')
          .col-sm-10
            %p.form-control-static= article.body.truncate(200)
        .form-inline.row
          .col-sm-10.col-sm-offset-2
            %button.button-admin-control{:type => "submit"}= link_to t('admin_form.show'), admin_article_path(article)
            %button.button-admin-control{:type => "submit"}= link_to t('admin_form.edit'), edit_admin_article_path(article)
            %button.button-admin-control{:type => "submit"}= link_to t('admin_form.destroy'), admin_article_path(article), method: :delete, data: { confirm: 'Are you sure?' }

app/views/admin/articles/new.html.haml
.article-body
  .container
    %h1=t('article.new')
    = render 'form', article: @article
    .row
      %button.button-admin-nav{:type => "submit"}= link_to t('admin_form.back'), admin_articles_path

app/views/admin/articles/show.html.haml
.article-body
  .container
    %h1=t('article.show')
    %form
      .form-group.row
        %label.bold-font.col-sm-2.checkbox=t('article.title')
        .col-sm-10
          %p.form-control-static= @article.title
      .form-group.row
        %label.bold-font.col-sm-2.checkbox=t('admin_form.content')
        .col-sm-10
          %p.form-control-static= @article.body
      .form-inline.row
        %button.button-admin-control{:type => "submit"}= link_to t('admin_form.edit'), edit_admin_article_path(@article)
        %button.button-admin-control{:type => "submit"}= link_to t('admin_form.back'), admin_articles_path

app/views/admin/products/_form.html.haml
= form_for [:admin, @product] do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this admin_product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg
  %form
    .form-group.row
      %label.bold-font=t('product.picture')
      = f.file_field :avatar
    .form-group.row
      %label.bold-font=t('admin_form.title')
      = f.text_field :title, require: true, class: 'form-control'
    .form-group.row
      %label.bold-font=t('product.price')
      = f.text_field :price, require: true, class: 'form-control'
    .form-group.row
      %label.bold-font=t('admin_form.description')
      = f.text_area :description, :cols => 50, :rows => 10, require: true, class: 'form-control'
    .form-group.row
      %label.bold-font=t('product.size')
      = f.text_field :size, require: true, class: 'form-control'
    .form-group.row
      %label.bold-font=t('admin_form.other')
      = f.text_area :other, :cols => 50, :rows => 10, require: true, class: 'form-control'    
    .form-group.row
      %button.button-admin-save.pull-right{:type => "submit"}=t('admin_form.save')

app/views/admin/products/edit.html.haml
.article-body
  .container
    %h1=t('product.edit')
    = render 'form'
    .form-inline.row
      %button.button-admin-nav{:type => "submit"}= link_to t('admin_form.show'), [:admin, @product]
      %button.button-admin-nav{:type => "submit"}= link_to t('admin_form.back'), admin_products_path

app/views/admin/products/index.html.haml
.article-body
  .container
    %h1=t('product.list')
    .form-group.row
      %button.button-admin-nav{:type => "submit"}= link_to t('product.new'), new_admin_product_path
    - @products.each do |product|
      %form.form-margin-bottom
        .form-group.row
          %label.bold-font.col-sm-2.checkbox=t('product.picture')
          .col-sm-10
            %p.form-control-static=image_tag product.avatar.url(:medium)
        .form-group.row
          %label.bold-font.col-sm-2.checkbox=t('admin_form.title')
          .col-sm-10
            %p.form-control-static= product.title
        .form-group.row
          %label.bold-font.col-sm-2.checkbox=t('admin_form.price')
          .col-sm-10
            %p.form-control-static= product.price
        .form-group.row
          %label.bold-font.col-sm-2.checkbox=t('admin_form.content')
          .col-sm-10
            %p.form-control-static= product.description
        .form-group.row
          %label.bold-font.col-sm-2.checkbox=t('admin_form.size')
          .col-sm-10
            %p.form-control-static= product.size
        .form-group.row
          %label.bold-font.col-sm-2.checkbox=t('admin_form.content')
          .col-sm-10
            %p.form-control-static= product.other
        .form-inline.row
          .col-sm-10.col-sm-offset-2
            %button.button-admin-control{:type => "submit"}= link_to t('admin_form.show'), admin_product_path(product)
            %button.button-admin-control{:type => "submit"}= link_to t('admin_form.edit'), edit_admin_product_path(product)
            %button.button-admin-control{:type => "submit"}= link_to t('admin_form.destroy'), [:admin, product], :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/admin/products/new.html.haml
.article-body
  .container
    %h1=t('product.new')
    = render 'form'
    .row
      %button.button-admin-nav{:type => "submit"}= link_to t('admin_form.back'), admin_products_path

app/views/admin/products/show.html.haml
.article-body
  .container
    %h1=t('product.show')
    %form
      .form-group.row
        %label.bold-font.col-sm-2.checkbox=t('product.picture')
        .col-sm-10
          %p.form-control-static= image_tag @product.avatar.url(:medium)
      .form-group.row
        %label.bold-font.col-sm-2.checkbox=t('admin_form.title')
        .col-sm-10
          %p.form-control-static= @product.title
      .form-group.row
        %label.bold-font.col-sm-2.checkbox=t('admin_form.price')
        .col-sm-10
          %p.form-control-static= @product.price
      .form-group.row
        %label.bold-font.col-sm-2.checkbox=t('admin_form.content')
        .col-sm-10
          %p.form-control-static= @product.description
      .form-group.row
        %label.bold-font.col-sm-2.checkbox=t('admin_form.size')
        .col-sm-10
          %p.form-control-static= @product.size
      .form-group.row
        %label.bold-font.col-sm-2.checkbox=t('admin_form.content')
        .col-sm-10
          %p.form-control-static= @product.other
      .form-inline.row
        %button.button-admin-control{:type => "submit"}= link_to t('admin_form.show'), edit_admin_product_path(@product)
        %button.button-admin-control{:type => "submit"}= link_to t('admin_form.back'), admin_products_path

app/views/admin/teams/_form.html.haml
= form_for [:admin, @team] do |f|
  - if @team.errors.any?
    #error_explanation
      %h2= "#{pluralize(@team.errors.count, "error")} prohibited this admin_team from being saved:"
      %ul
        - @team.errors.full_messages.each do |msg|
          %li= msg
  %form
    .form-group.row
      %label.bold-font=t('team_member.picture')
      = f.file_field :avatar
    .form-group.row
      %label.bold-font=t('admin_form.name')
      = f.text_field :name, require: true, class: 'form-control'
    .form-group.row
      %label.bold-font=t('team_member.bio')
      = f.text_field :bio, require: true, class: 'form-control'
    .form-group.row
      %label.bold-font=t('team_member.sponsors')
      = f.text_area :sponsors, :cols => 50, :rows => 10, require: true, class: 'form-control'
    .form-group.row
      %button.button-admin-save.pull-right{:type => "submit"}=t('admin_form.save')

app/views/admin/teams/edit.html.haml
.article-body
  .container
    %h1=t('team.edit')
    = render 'form'
    .form-inline.row
      %button.button-admin-nav{:type => "submit"}= link_to t('admin_form.show'), [:admin, @team]
      %button.button-admin-nav{:type => "submit"}= link_to t('admin_form.back'), admin_teams_path

app/views/admin/teams/index.html.haml
.article-body
  .container
    %h1=t('team.list')
    .form-group.row
      %button.button-admin-nav{:type => "submit"}= link_to t('team.new'), new_admin_team_path
    - @teams.each do |team|
      %form.form-margin-bottom
        .form-group.row
          %label.bold-font.col-sm-2.checkbox=t('team.picture')
          .col-sm-10
            %p.form-control-static=image_tag team.avatar.url(:medium)
        .form-group.row
          %label.bold-font.col-sm-2.checkbox=t('admin_form.name')
          .col-sm-10
            %p.form-control-static= team.name
        .form-group.row
          %label.bold-font.col-sm-2.checkbox=t('team.bio')
          .col-sm-10
            %p.form-control-static= team.bio
        .form-group.row
          %label.bold-font.col-sm-2.checkbox=t('admin_form.sponsors')
          .col-sm-10
            %p.form-control-static= team.sponsors
        .form-inline.row
          .col-sm-10.col-sm-offset-2
            %button.button-admin-control{:type => "submit"}= link_to t('admin_form.show'), admin_team_path(team)
            %button.button-admin-control{:type => "submit"}= link_to t('admin_form.edit'), edit_admin_team_path(team)
            %button.button-admin-control{:type => "submit"}= link_to t('admin_form.destroy'), [:admin, team], :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/admin/teams/new.html.haml
.article-body
  .container
    %h1=t('team.new')
    = render 'form'
    .row
      %button.button-admin-nav{:type => "submit"}= link_to t('admin_form.back'), admin_teams_path

app/views/admin/teams/show.html.haml
.article-body
  .container
    %h1=t('team.show')
    %form
      .form-group.row
        %label.bold-font.col-sm-2.checkbox=t('team.picture')
        .col-sm-10
          %p.form-control-static= image_tag @team.avatar.url(:medium)
      .form-group.row
        %label.bold-font.col-sm-2.checkbox=t('admin_form.name')
        .col-sm-10
          %p.form-control-static= @team.name
      .form-group.row
        %label.bold-font.col-sm-2.checkbox=t('team.bio')
        .col-sm-10
          %p.form-control-static= @team.bio
      .form-group.row
        %label.bold-font.col-sm-2.checkbox=t('admin_form.sponsors')
        .col-sm-10
          %p.form-control-static= @team.sponsors
      .form-inline.row
        %button.button-admin-control{:type => "submit"}= link_to t('admin_form.show'), edit_admin_team_path(@team)
        %button.button-admin-control{:type => "submit"}= link_to t('admin_form.back'), admin_teams_path

app/views/articles/index.html.haml
= render 'partials/nav'
#section-news
  .container-fluid
    - @articles.each do |article|
      .form-group.row
        .date-article.bold-font.col-md-1.col-md-offset-1.col-sm-2.col-xs-2 24.05
        .col-md-8.col-md-offset-1.col-sm-8.col-sm-offset-1.col-xs-8.col-xs-offset-1
          %h1.form-control-static= article.title
          %p.form-control-static= article.body.truncate(200)
      .form-group.row
        .col-md-1.col-md-offset-10.col-sm-1.col-sm-offset-10.col-xs-1.col-xs-offset-8
          = link_to t('home_general.more'), class: 'button button-news'

app/views/articles/show.html.haml
= render 'partials/nav'
#section-news-show
  .container-fluid
    .row
      .date-article.bold-font.col-md-1.col-md-offset-1.col-sm-2.col-xs-2 24.05
      .col-md-8.col-md-offset-1.col-sm-8.col-sm-offset-1.col-xs-8.col-xs-offset-1
        %h1= @article.title
        %p= @article.body
    .row
      .col-md-1.col-md-offset-10.col-sm-1.col-sm-offset-10.col-xs-1.col-xs-offset-8
        

app/views/frontpage/index.html.haml
= render '_partials/nav'
= render '_partials/header'
= render '_partials/about'
= render '_partials/contact'
= render '_partials/footer'

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Assistant:300,400,600,700,800", :rel => "stylesheet"}/
    %link{:href => "//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css", :rel => "stylesheet"}/
    %title NothingWrong
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %nav.navbar.navbar-nav.navbar-fixed-top.navbar-admin
      .navbar-header
        %button.c-hamburger.c-hamburger--htx.collapsed.visible-sm.visible-xs.pull-right{"aria-expanded" => "false", "data-target" => "#navbar-collapse-2", "data-toggle" => "collapse", :type => "button"}
          %span toggle menu
      %ul.nav.navbar-nav.visible-md.visible-lg
        %li= link_to t('menu_admin.articles'), admin_articles_path
        %li= link_to t('menu_admin.team'), admin_teams_path
        %li= link_to t('menu_admin.products'), admin_products_path
      .hidden-lg.hidden-md
        .collapse.navbar-collapse#navbar-collapse-2
          %ul.nav.navbar-nav.nav-menu.mobile-menu
            %li= link_to t('menu_admin.articles'), admin_articles_path
            %li= link_to t('menu_admin.team'), admin_teams_path
            %li= link_to t('menu_admin.products'), admin_products_path
  %body#admin-body
    = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Assistant:300,400,600,700,800", :rel => "stylesheet"}/
    %link{:href => "//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css", :rel => "stylesheet"}/
    %title NothingWrong
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield